---
languages: [fr_FR,en_US,es_ES,de_DE]
exclude_from_localizations: ["assets", "css", "js","img"]
defaultLang: fr_FR
baseurl: "/"
sass:
  sass_dir: css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
- jekyll-seo-tag
exclude:
- vendor
plugins:
- jekyll-seo-tag
title: "Documentation Jeedom"
description: "Ceci est la documentation, lier à la solution domotique Jeedom."
author: "Jeedom"
image: https://www.jeedom.com/site/logo.png
twitter:
  username: Jeedom_domotic
social:
  name: Jeedom
  links:
    - https://twitter.com/Jeedom_domotic
    - https://www.facebook.com/Jeedom-249936178537210/
    - https://github.com/jeedom
t:
  en_US:
    presentation : "Présentation"
    installation : "Installation"
    start_smart : "Start Jeedom Smart"
    start_pro : "Start Jeedom Pro"
    first_step : "Premiers-pas"
    backup_cloud : "Backup cloud"
    voice_assist : "Assistant vocaux"
    cloud_monitoring : "Monitoring"
    remote_access : "Accès distant"
    user_manuel : "Manuel d'utilisation"
    dashboard : "Dashboard"
    view : "Vues"
    design : "Design"
    design_3D : "Design 3D"
    administration : "Administration"
    save : "Sauvegarde"
    update : "Mise à jour"
    security : "Sécurité"
    home_protocol : "Protocole domotique"
    home_gateway : "Passerelle domotique"
    programming : "Programmation"
    organize : "Organisation"
    weatcher : "Météo"
    communication : "Communication"
    connected_object : "Objets connectés"
    multimedia : "Multimédia"
    confort : "Confort"
    monitoring : "Monitoring"
    health : "Santé"
    natrue : "Nature"
    automate : "Automatisme"
    energy : "Energie"
    other : "Autre"
    ticket : "Assitance et bug"
  fr_FR:
    introduction: "Introduction"
    presentation : "Présentation"
    installation : "Installation"
    start_smart : "Start Jeedom Smart"
    start_pro : "Start Jeedom Pro"
    first_step : "Premiers-pas"
    backup_cloud : "Backup cloud"
    voice_assist : "Assistant vocaux"
    cloud_monitoring : "Monitoring"
    remote_access : "Accès distant"
    user_manuel : "Manuel d'utilisation"
    dashboard : "Dashboard"
    view : "Vues"
    design : "Design"
    design_3D : "Design 3D"
    administration : "Administration"
    save : "Sauvegarde"
    update : "Mise à jour"
    security : "Sécurité"
    home_protocol : "Protocole domotique"
    home_gateway : "Passerelle domotique"
    programming : "Programmation"
    organize : "Organisation"
    weatcher : "Météo"
    communication : "Communication"
    connected_object : "Objets connectés"
    multimedia : "Multimédia"
    confort : "Confort"
    monitoring : "Monitoring"
    health : "Santé"
    natrue : "Nature"
    automate : "Automatisme"
    energy : "Energie"
    other : "Autre"
    ticket : "Assitance et bug"
  es_ES:
    presentation : "Présentation"
    installation : "Installation"
    start_smart : "Start Jeedom Smart"
    start_pro : "Start Jeedom Pro"
    first_step : "Premiers-pas"
    backup_cloud : "Backup cloud"
    voice_assist : "Assistant vocaux"
    cloud_monitoring : "Monitoring"
    remote_access : "Accès distant"
    user_manuel : "Manuel d'utilisation"
    dashboard : "Dashboard"
    view : "Vues"
    design : "Design"
    design_3D : "Design 3D"
    administration : "Administration"
    save : "Sauvegarde"
    update : "Mise à jour"
    security : "Sécurité"
    home_protocol : "Protocole domotique"
    home_gateway : "Passerelle domotique"
    programming : "Programmation"
    organize : "Organisation"
    weatcher : "Météo"
    communication : "Communication"
    connected_object : "Objets connectés"
    multimedia : "Multimédia"
    confort : "Confort"
    monitoring : "Monitoring"
    health : "Santé"
    natrue : "Nature"
    automate : "Automatisme"
    energy : "Energie"
    other : "Autre"
    ticket : "Assitance et bug"
  de_DE:
    presentation : "Présentation"
    installation : "Installation"
    start_smart : "Start Jeedom Smart"
    start_pro : "Start Jeedom Pro"
    first_step : "Premiers-pas"
    backup_cloud : "Backup cloud"
    voice_assist : "Assistant vocaux"
    cloud_monitoring : "Monitoring"
    remote_access : "Accès distant"
    user_manuel : "Manuel d'utilisation"
    dashboard : "Dashboard"
    view : "Vues"
    design : "Design"
    design_3D : "Design 3D"
    administration : "Administration"
    save : "Sauvegarde"
    update : "Mise à jour"
    security : "Sécurité"
    home_protocol : "Protocole domotique"
    home_gateway : "Passerelle domotique"
    programming : "Programmation"
    organize : "Organisation"
    weatcher : "Météo"
    communication : "Communication"
    connected_object : "Objets connectés"
    multimedia : "Multimédia"
    confort : "Confort"
    monitoring : "Monitoring"
    health : "Santé"
    natrue : "Nature"
    automate : "Automatisme"
    energy : "Energie"
    other : "Autre"
    ticket : "Assitance et bug"
